language: python
python:
  - "3.9"
addons:
  apt:
    update: true
    packages:
      - ffmpeg
before_install:
  - pip install poetry
install:
  - poetry install
script:
  - ./static-analysis.sh
  - ./test.sh