language: python
python:
  - "3.9"
addons:
  apt:
    update: true
    packages:
      - ffmpeg
before_install:
  - pip install poetry
install:
  - poetry install
script:
  - ./static-analysis.sh
  - ./test.sh
deploy:
  provider: script
  on:
    repo: DMR-coding/zoom-narrator
    tags: true
  script: poetry publish --build --username __token__ --password $PYPI_PASS